name: E2E Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    e2e-tests:
        name: 'E2E Tests (${{ matrix.wp }})'
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental == true }}
        strategy:
            fail-fast: false
            matrix:
                wp: ['latest']
                experimental: [false]
                include:
                    - wp: 'trunk'
                      experimental: true
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Build plugin
              run: npm run build

            - name: Configure WordPress version
              run: |
                  if [[ $WP_VERSION == 'trunk' ]]; then
                    echo "Using WordPress trunk"
                    echo "{\"core\":\"WordPress/WordPress#master\"}" >> .wp-env.override.json
                  fi
              env:
                  WP_VERSION: ${{ matrix.wp }}

            - name: Install WordPress
              run: |
                  chmod -R 767 ./ # TODO: Possibly integrate in wp-env
                  npm run wp-env start

            - name: Run tests
              run: npm run test:e2e

            - name: Archive debug artifacts (screenshots, HTML snapshots)
              uses: actions/upload-artifact@v7
              if: always()
              with:
                  name: failures-artifacts-${{ matrix.wp }}
                  path: artifacts
